name: CI

on:
  push:
    paths:
      - "**/*.go"
      - "**/*.tf"
    branches:
      - main
      - dev
  pull_request:
    branches:
      - "**"


jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Download Go modules
        run: go mod download

      - name: Build Go project
        run: go build ./...

      - name: Run Go tests
        run: go test ./...